name: Build and Deploy DocFX

on:
  push:
    branches:
      - master

jobs:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v1
    
    
    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: UnitySample/Documentation/docfx.json
        

    # Publish generated site using GitHub Pages
    - name: Publish Documentation on GitHub Pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.ACCESS_TOKEN }} # See https://github.com/maxheld83/ghpages
