name: Build and Deploy DocFX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    
    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: UnitySample/Documentation/docfx.json
        
        
    # Upload the generated documentation
    - name: Upload site artifact
      uses: actions/upload-artifact@v1
      with:
        name: _site
        path: UnitySample/Documentation/_site # Must equals the 'build.dest' value on your docfx.json


    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: Korstrix/korstrix.github.io
        publish_branch: master  # default: gh-pages
        publish_dir: ./UnitySample/Documentation/_site
