name: Build and Deploy DocFX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    
    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: UnitySample/Documentation/docfx.json
        
    # Upload the generated documentation
    - name: Upload site artifact
      uses: actions/upload-artifact@v1
      with:
        name: _site
        path: UnitySample/Documentation/_site # Must equals the 'build.dest' value on your docfx.json

    # Publish generated site using GitHub Pages
    - name: Publish Documentation on GitHub Pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: UnitySample/Documentation/_site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.ACCESS_TOKEN }} # See https://github.com/maxheld83/ghpages
    
    - name: Copycat
      uses: andstor/copycat-action@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        username: KorStrixCI
        src_branch: master
        src_path: /.
        dst_owner: KorStrix
        dst_repo_name: korstrix.github.io
        dst_branch: master
        dst_path: /DocFXSample/
        clean: true
        exclude: .*
