name: Build and Deploy DocFX

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    
    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: UnitySample/Documentation/docfx.json

  #deploy:
    #needs: build
    #runs-on: ubuntu-latest
    
    #steps:
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        external_repository: Korstrix/korstrix.github.io
        publish_branch: master
        keep_files: true

        publish_dir: ./UnitySample/Documentation/_site
        destination_dir: DocFXSample/
